/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary - Medical Blue
        primary: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
        // Secondary - Healthcare Green
        secondary: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
          950: "#052e16",
        },
        // Semantic colors
        success: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
        },
        error: {
          50: "#fef2f2",
          100: "#fee2e2",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "#ef4444",
          600: "#dc2626",
          700: "#b91c1c",
          800: "#991b1b",
          900: "#7f1d1d",
        },
        warning: {
          50: "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
          800: "#92400e",
          900: "#78350f",
        },
        // Extend Tailwind's neutral with more shades
        neutral: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        // Semantic theme colors using CSS variables
        background: {
          primary: "var(--color-background-primary)",
          secondary: "var(--color-background-secondary)",
          tertiary: "var(--color-background-tertiary)",
          elevated: "var(--color-background-elevated)",
          overlay: "var(--color-background-overlay)",
          inverse: "var(--color-background-inverse)",
        },
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          disabled: "var(--color-text-disabled)",
          inverse: "var(--color-text-inverse)",
          link: "var(--color-text-link)",
          "link-hover": "var(--color-text-link-hover)",
          success: "var(--color-text-success)",
          error: "var(--color-text-error)",
          warning: "var(--color-text-warning)",
        },
        border: {
          default: "var(--color-border-default)",
          subtle: "var(--color-border-subtle)",
          strong: "var(--color-border-strong)",
          focus: "var(--color-border-focus)",
          success: "var(--color-border-success)",
          error: "var(--color-border-error)",
          warning: "var(--color-border-warning)",
        },
        surface: {
          card: "var(--color-surface-card)",
          "card-hover": "var(--color-surface-card-hover)",
          input: "var(--color-surface-input)",
          "input-hover": "var(--color-surface-input-hover)",
          "input-focus": "var(--color-surface-input-focus)",
          "button-primary": "var(--color-surface-button-primary)",
          "button-primary-hover": "var(--color-surface-button-primary-hover)",
          "button-secondary": "var(--color-surface-button-secondary)",
          "button-secondary-hover":
            "var(--color-surface-button-secondary-hover)",
          "button-outline": "var(--color-surface-button-outline)",
          "button-outline-hover": "var(--color-surface-button-outline-hover)",
          "button-ghost": "var(--color-surface-button-ghost)",
          "button-ghost-hover": "var(--color-surface-button-ghost-hover)",
          "button-danger": "var(--color-surface-button-danger)",
          "button-danger-hover": "var(--color-surface-button-danger-hover)",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          "sans-serif",
        ],
        mono: [
          '"JetBrains Mono"',
          '"SF Mono"',
          "Monaco",
          "Inconsolata",
          '"Fira Code"',
          "Consolas",
          '"Courier New"',
          "monospace",
        ],
      },
      transitionDuration: {
        normal: "200ms",
        fast: "150ms",
        slow: "300ms",
      },
    },
  },
  plugins: [],
};
